%% TUGBOAT FEEDBACK-LINEARIZATION SIMULATION
% Run RSC.m first. This script uses route_points generated by RSC.m.

%% Parameters

dt_sim = 0.01;          % Simulation sample time
desired_speed = 0.8;    % Approximate reference speed [m/s]
lambda = 0.8;           % Feedback-linearization bandwidth [1/s]

nx = 8;                 % [X; Y; psi; ub; vb; r; F_L; F_R]
nu = 2;                 % [F_L_cmd; F_R_cmd]

% Input limits
u_max = 100;
u_min = -100;

%% Waypoints extraction from route_points
% Remove consecutive duplicate route points
waypoints = route_points;
point_difference = diff(waypoints, 1, 1);
keep_point = [true; vecnorm(point_difference, 2, 2) > 1e-9];
waypoints = waypoints(keep_point, :);

if size(waypoints, 1) < 2
    error('route_points must contain at least two different points.');
end

%% Quintic trajectory timing

segment_distance = vecnorm(diff(waypoints, 1, 1), 2, 2);
segment_duration = max(segment_distance / desired_speed, 2.0);
segment_start_time = [0; cumsum(segment_duration)];

total_time = segment_start_time(end);
time = 0:dt_sim:total_time;
T = numel(time);

%% Initialization

initial_direction = waypoints(2,:) - waypoints(1,:);
psi0 = atan2(initial_direction(2), initial_direction(1));

% State: [X; Y; psi; ub; vb; r; F_L; F_R]
x_robot = [waypoints(1,1); waypoints(1,2); psi0; 0; 0; 0; 0; 0];

history_x = zeros(nx, T);
history_u = zeros(nu, T);
history_ref = zeros(2, T);
history_error = zeros(2, T);
history_condition = zeros(1, T);
history_saturation = false(nu, T);

history_x(:,1) = x_robot;

%% Simulation Loop

for t = 1:T-1
    current_time = time(t);

    [p_d, v_d, a_d, j_d] = quintic_route_reference( ...
        current_time, waypoints, ...
        segment_start_time, segment_duration);

    [u_cmd, debug] = feedback_linearization_controller( ...
        x_robot, p_d, v_d, a_d, j_d, lambda, u_min, u_max);

    history_ref(:,t) = p_d;
    history_u(:,t) = u_cmd;
    history_error(:,t) = debug.position_error;
    history_condition(t) = debug.condition_number;
    history_saturation(:,t) = ...
        abs(debug.command_unsaturated - debug.command_saturated) > 1e-8;

    % Zero-order hold on u_cmd and RK4 propagation of the nonlinear plant.
    k1 = tugboat3d(x_robot, u_cmd);
    k2 = tugboat3d(x_robot + 0.5*dt_sim*k1, u_cmd);
    k3 = tugboat3d(x_robot + 0.5*dt_sim*k2, u_cmd);
    k4 = tugboat3d(x_robot + dt_sim*k3, u_cmd);

    x_robot = x_robot + (dt_sim/6)*(k1 + 2*k2 + 2*k3 + k4);

    % Wrap heading to [-pi, pi].
    x_robot(3) = atan2(sin(x_robot(3)), cos(x_robot(3)));

    history_x(:,t+1) = x_robot;
end

%% Store final sample

[p_d, v_d, a_d, j_d] = quintic_route_reference( ...
    time(end), waypoints, ...
    segment_start_time, segment_duration);

history_ref(:,end) = p_d;
history_u(:,end) = history_u(:,end-1);
history_error(:,end) = history_x(1:2,end) - p_d;
history_condition(end) = history_condition(end-1);
history_saturation(:,end) = history_saturation(:,end-1);

%% Plotting

figWidth  = 15;
figHeight = 12;

% --- Ana Harita ve Rota Grafiği ---
fig1 = figure('WindowState','maximized', 'Color','w');
ax1 = gca; hold on; axis equal;
xlim([W(1) W(2)]); ylim([W(3) W(4)]);
set(ax1, 'XTick', [], 'YTick', [], 'Box', 'on', 'LineWidth', 1);

% Remove Margins for Main Map
set(ax1, 'LooseInset', [0,0,0,0]);
ax1.Position = [0 0 1 1];

for i = 1:numel(obs)
    plot(obs{i}, 'FaceColor',[0 0 0], 'FaceAlpha',0.6, 'EdgeColor','none');
end

if ~isempty(pathIds)
    for k = 1:length(pathIds)
        node_idx = pathIds(k);
        plot(nodes(node_idx).poly, 'FaceColor',[1.0 0.85 0.7], 'FaceAlpha',0.40, ...
            'EdgeColor',[1.0 0.5 0.0], 'LineWidth',1.5);
    end
    plot(waypoints(:,1), waypoints(:,2), 'bo--', 'MarkerSize',6, 'LineWidth',1.5);
end

plot(history_ref(1,:), history_ref(2,:), 'b--', 'LineWidth',1.5);
plot(history_x(1,:), history_x(2,:), 'r-', 'LineWidth',2);
plot(q_start(1), q_start(2), 'go', 'MarkerSize',9, 'LineWidth',2);
text(q_start(1), q_start(2), '  start', 'FontSize',12, 'FontWeight','bold');
plot(q_goal(1), q_goal(2), 'ro', 'MarkerSize',9, 'LineWidth',2);
text(q_goal(1), q_goal(2), '  goal', 'FontSize',12, 'FontWeight','bold');

% --- Kontrol Girişleri Grafiği ---
t_vec = (0:size(history_u,2)-1) * dt_sim;
fig2 = figure('Units','centimeters', 'Position',[2, 2, figWidth, figHeight], 'Color','w');
tlo2 = tiledlayout(2,1,'Padding','tight','TileSpacing','compact');

nexttile;
plot(t_vec, history_u(1,:), 'r', 'LineWidth',1.5);
grid on; set(gca, 'XTickLabel', [], 'Box', 'on');
ylabel('F_{left_cmd} (N)');

nexttile;
plot(t_vec, history_u(2,:), 'r', 'LineWidth',1.5);
grid on; set(gca, 'Box', 'on');
xlabel('Time [s]');
ylabel('F_{right_cmd} (N)');

% --- Durum Değişkenleri Grafiği ---
fig3 = figure('Units','centimeters', 'Position',[figWidth+3, 2, figWidth, figHeight], 'Color','w');
time_axis = (0:size(history_x,2)-1)*dt_sim;
tlo3 = tiledlayout(3,1,'Padding','tight','TileSpacing','compact');

nexttile;
plot(time_axis, history_x(3,:), 'k', 'LineWidth',1.5);
grid on; set(gca, 'XTickLabel', [], 'YTickLabel', [], 'Box', 'on');
ylabel('Heading');

nexttile;
plot(time_axis, history_x(4,:), 'b', 'LineWidth',1.5); hold on;
plot(time_axis, history_x(5,:), 'r', 'LineWidth',1.5);
grid on; set(gca, 'XTickLabel', [], 'YTickLabel', [], 'Box', 'on');
ylabel('Velocities');

nexttile;
plot(time_axis, history_x(6,:), 'm', 'LineWidth',1.5);
grid on; set(gca, 'XTickLabel', [], 'YTickLabel', [], 'Box', 'on');
ylabel('Yaw Rate');
xlabel('Time [s]');

%% Position tracking errors

fig4 = figure( ...
    'Units','centimeters', ...
    'Position',[2,2,figWidth,figHeight], ...
    'Color','w');

tlo4 = tiledlayout(fig4,2,1, ...
    'Padding','tight', ...
    'TileSpacing','compact');

% X error
ax4_1 = nexttile(tlo4);

plot(ax4_1, time_axis, history_error(1,:), ...
    'b-', 'LineWidth',1.5);

grid(ax4_1,'on');
set(ax4_1,'XTickLabel',[],'Box','on');

ylabel(ax4_1,'e_X [m]');

% Y error
ax4_2 = nexttile(tlo4);

plot(ax4_2, time_axis, history_error(2,:), ...
    'r-', 'LineWidth',1.5);

grid(ax4_2,'on');
set(ax4_2,'Box','on');

xlabel(ax4_2,'Time [s]');
ylabel(ax4_2,'e_Y [m]');

title(tlo4,'Position Tracking Errors');

%% Common and differential thrust

F_sum_cmd  = history_u(1,:) + history_u(2,:);
F_diff_cmd = history_u(1,:) - history_u(2,:);

F_sum_actual  = history_x(7,:) + history_x(8,:);
F_diff_actual = history_x(7,:) - history_x(8,:);

fig5 = figure( ...
    'Units','centimeters', ...
    'Position',[figWidth+3,2,figWidth,figHeight], ...
    'Color','w');

tlo5 = tiledlayout(fig5,2,1, ...
    'Padding','tight', ...
    'TileSpacing','compact');

% Common thrust
ax5_1 = nexttile(tlo5);

plot(ax5_1, time_axis, F_sum_cmd, ...
    'b-', 'LineWidth',1.5);

hold(ax5_1,'on');

plot(ax5_1, time_axis, F_sum_actual, ...
    'k--', 'LineWidth',1.3);

grid(ax5_1,'on');
set(ax5_1,'XTickLabel',[],'Box','on');

ylabel(ax5_1,'F_L + F_R [N]');
legend(ax5_1,'Commanded','Actual','Location','best');

% Differential thrust
ax5_2 = nexttile(tlo5);

plot(ax5_2, time_axis, F_diff_cmd, ...
    'r-', 'LineWidth',1.5);

hold(ax5_2,'on');

plot(ax5_2, time_axis, F_diff_actual, ...
    'k--', 'LineWidth',1.3);

grid(ax5_2,'on');
set(ax5_2,'Box','on');

xlabel(ax5_2,'Time [s]');
ylabel(ax5_2,'F_L - F_R [N]');
legend(ax5_2,'Commanded','Actual','Location','best');

title(tlo5,'Common and Differential Thrust');

%% Print results

final_error = history_x(1:2,end) - waypoints(end,:).';

fprintf('\nFeedback-linearization simulation completed.\n');
fprintf('Total simulation time: %.2f s\n', total_time);
fprintf('Final X error: %.4f m\n', final_error(1));
fprintf('Final Y error: %.4f m\n', final_error(2));
fprintf('Final position error magnitude: %.4f m\n', norm(final_error));
fprintf('Maximum cond(Delta): %.4e\n', max(history_condition));
fprintf('Saturated steps: %d of %d\n', ...
    sum(any(history_saturation,1)), T);


function [u_cmd, debug] = feedback_linearization_controller( ...
    x, p_d, v_d, a_d, j_d, lambda, u_min, u_max)
%FEEDBACK_LINEARIZATION_CONTROLLER Cartesian position controller.

    % Feedback gains obtained from (s + lambda)^3.
    K0 = lambda^3 * eye(2);
    K1 = 3*lambda^2 * eye(2);
    K2 = 3*lambda * eye(2);

    [p, p_dot, p_ddot] = position_derivatives(x);

    % f(x) in xdot = f(x) + G*u_cmd.
    f = tugboat3d(x, [0; 0]);

    % p_dddot = b(x) + Delta(x)*u_cmd.
    H = numerical_jacobian(@position_acceleration, x);
    b = H*f;
    Delta = decoupling_matrix(x);

    e0 = p      - p_d;
    e1 = p_dot  - v_d;
    e2 = p_ddot - a_d;

    virtual_input = j_d - K2*e2 - K1*e1 - K0*e0;
    control_rhs = virtual_input - b;

    if rcond(Delta) < 1e-8
        damping = 1e-4;
        u_cmd = Delta' * ...
            ((Delta*Delta' + damping*eye(2)) \ control_rhs);
    else
        u_cmd = Delta \ control_rhs;
    end

    u_cmd_unsaturated = u_cmd;
    u_cmd = min(max(u_cmd, u_min), u_max);

    debug.position = p;
    debug.velocity = p_dot;
    debug.acceleration = p_ddot;
    debug.position_error = e0;
    debug.velocity_error = e1;
    debug.acceleration_error = e2;
    debug.drift = b;
    debug.decoupling_matrix = Delta;
    debug.condition_number = cond(Delta);
    debug.virtual_input = virtual_input;
    debug.command_unsaturated = u_cmd_unsaturated;
    debug.command_saturated = u_cmd;
end


function Delta = decoupling_matrix(x)
%DECOUPLING_MATRIX Analytical input-output decoupling matrix.

    m  = 10.2;
    Iz = 0.63994;

    beam = 0.29;
    d = beam/2;

    Xudot = -0.87818;
    Yvdot = -1.05279;
    Yrdot = -1.92760;
    Nrdot = -0.04531;

    T_L = 0.25;
    T_R = 0.25;

    M = [m - Xudot,      0,            0;
         0,              m - Yvdot,   -Yrdot;
         0,             -Yrdot,        Iz - Nrdot];

    B_prop = [1, 1;
              0, 0;
              d, -d];

    E = [1, 0, 0;
         0, 1, 0];

    psi = x(3);

    R = [cos(psi), -sin(psi);
         sin(psi),  cos(psi)];

    T_inv = diag([1/T_L, 1/T_R]);

    Delta = R * E * (M \ B_prop) * T_inv;
end


function [p, p_dot, p_ddot] = position_derivatives(x)
%POSITION_DERIVATIVES Inertial position derivatives.

    psi = x(3);
    ub = x(4);
    vb = x(5);
    r = x(6);

    nu_xy = [ub; vb];

    R = [cos(psi), -sin(psi);
         sin(psi),  cos(psi)];

    S = [0, -1;
         1,  0];

    p = x(1:2);
    p_dot = R*nu_xy;

    % With a zero command, actual forces x(7:8) still act on the vessel.
    xdot = tugboat3d(x, [0; 0]);
    nu_dot_xy = xdot(4:5);

    R_dot = r*R*S;
    p_ddot = R_dot*nu_xy + R*nu_dot_xy;
end


function p_ddot = position_acceleration(x)
%POSITION_ACCELERATION Inertial position acceleration only.

    [~, ~, p_ddot] = position_derivatives(x);
end


function J = numerical_jacobian(fun, x)
%NUMERICAL_JACOBIAN Central finite-difference Jacobian.

    x = x(:);
    f0 = fun(x);

    ny = numel(f0);
    nx = numel(x);
    J = zeros(ny,nx);

    for i = 1:nx
        step = 1e-6 * max(1, abs(x(i)));

        x_plus = x;
        x_minus = x;

        x_plus(i) = x_plus(i) + step;
        x_minus(i) = x_minus(i) - step;

        J(:,i) = (fun(x_plus) - fun(x_minus)) / (2*step);
    end
end


function xdot = tugboat3d(x, u_cmd)
%TUGBOAT3D Nonlinear 3-DOF vessel with actuator dynamics.
%
% State:
%   x = [X; Y; psi; ub; vb; r; F_L; F_R]
%
% Input:
%   u_cmd = [F_L_cmd; F_R_cmd]

    % Parameters
    m  = 10.2;
    Iz = 0.63994;

    % Geometry
    beam = 0.29;
    d = beam/2;

    % Actuator time constants
    T_L = 0.25;
    T_R = 0.25;

    % Identified hydrodynamic derivatives
    Xu    = -5.76909;
    Xuu   = -2.17161;
    Xudot = -0.87818;

    Yv    = -3.98659;
    Yr    = -0.0001;
    Yvv   = -3.95131;
    Yvdot = -1.05279;
    Yrdot = -1.92760;

    Nv    = -0.0001;
    Nr    = -0.12392;
    Nrr   = -0.33077;
    Nrdot = -0.04531;

    % States
    eta = x(1:3);
    nu = x(4:6);
    F = x(7:8);

    psi = eta(3);
    ub = nu(1);
    vb = nu(2);
    r = nu(3);

    % Thruster allocation
    B_prop = [1, 1;
              0, 0;
              d, -d];

    tau = B_prop*F;

    % Inertia matrix
    M = [m - Xudot,      0,            0;
         0,              m - Yvdot,   -Yrdot;
         0,             -Yrdot,        Iz - Nrdot];

    % Coriolis and centripetal matrix
    C = [0, 0, -((m - Yvdot)*vb - Yrdot*r);
         0, 0,  (m - Xudot)*ub;
         (m - Yvdot)*vb - Yrdot*r, -(m - Xudot)*ub, 0];

    % Linear and nonlinear damping matrix
    D = [-Xu - Xuu*abs(ub),                  0,                 0;
                          0, -Yv - Yvv*abs(vb),               -Yr;
                          0,                -Nv, -Nr - Nrr*abs(r)];

    nu_dot = M \ (tau - C*nu - D*nu);

    % Kinematics
    J = [cos(psi), -sin(psi), 0;
         sin(psi),  cos(psi), 0;
                0,         0, 1];

    eta_dot = J*nu;

    % First-order actuator dynamics
    F_dot = [(u_cmd(1) - F(1))/T_L;
             (u_cmd(2) - F(2))/T_R];

    xdot = [eta_dot;
            nu_dot;
            F_dot];
end


function [p_d, v_d, a_d, j_d] = quintic_route_reference( ...
    t, route_points, segment_start_time, segment_duration)
%QUINTIC_ROUTE_REFERENCE Quintic interpolation between RSC route points.

    number_of_segments = size(route_points,1) - 1;

    if t >= segment_start_time(end)
        p_d = route_points(end,:).';
        v_d = zeros(2,1);
        a_d = zeros(2,1);
        j_d = zeros(2,1);
        return;
    end

    segment = find(t >= segment_start_time(1:end-1), 1, 'last');
    segment = min(segment, number_of_segments);

    t0 = segment_start_time(segment);
    T = segment_duration(segment);

    s = (t - t0)/T;
    s = min(max(s,0),1);

    % blend = 10*s^3 - 15*s^4 + 6*s^5;
    % blend_dot = (30*s^2 - 60*s^3 + 30*s^4)/T;
    % blend_ddot = (60*s - 180*s^2 + 120*s^3)/T^2;
    % blend_dddot = (60 - 360*s + 360*s^2)/T^3;

    blend = 35*s^4 - 84*s^5 + 70*s^6 - 20*s^7;
    blend_dot = (140*s^3 - 420*s^4 + 420*s^5 - 140*s^6) / T;
    blend_ddot = (420*s^2 - 1680*s^3 + 2100*s^4 - 840*s^5) / T^2;
    blend_dddot = (840*s - 5040*s^2 + 8400*s^3 - 4200*s^4) / T^3;

    p0 = route_points(segment,:).';
    p1 = route_points(segment+1,:).';
    delta_p = p1 - p0;

    p_d = p0 + blend*delta_p;
    v_d = blend_dot*delta_p;
    a_d = blend_ddot*delta_p;
    j_d = blend_dddot*delta_p;
end
